name: Integrational tests
on:
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'

jobs:
  run-tests:
    name: Run Intergrational tests using Kind
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.9.0"

      - name: Deploy to Kuberenetes
        run: |-
          kubectl create configmap hazelcast-configuration --from-file=server/hazelcast.yaml
          kubectl create secret generic keystore --from-file=server/keystore --from-file=server/truststore --from-literal keystorePassword=123456 --from-literal truststorePassword=123456
          kubectl create secret generic hz-license-key --from-literal license=${{ secrets.LICENSE }}
          kubectl apply -f server/rbac.yaml
          kubectl apply -f server/statefulset.yaml

      - name: Test for successful Deployment
        run: |-
          kubectl wait --for=condition=ready pod/hazelcast-0 --timeout=150s
          kubectl wait --for=condition=ready pod/hazelcast-1 --timeout=150s
          kubectl wait --for=condition=ready pod/hazelcast-2 --timeout=150s

      - name: Check for SSL enabled
        id: ssl_check
        run: |-
          sslEnabledLog=$(kubectl logs pod/hazelcast-0 | grep "SSL is enabled")
          echo "::set-output name=ssl_log::$sslEnabledLog"

      - name: Deploy client
        id: client
        run: |-
          kubectl apply -f client/deployment.yaml
          podName=$(kubectl get pods --selector='app=hazelcast-client' --output=jsonpath={.items..metadata.name})
          kubectl wait --for=condition=ready pod/$podName --timeout=200s
          # sleep for 10 seconds so that Spring application is started
          sleep 10
          members=$(kubectl logs pod/$podName | grep "Members")
          echo "::set-output name=members::$members"

      - name: Fail if SSL not enabled
        if: (!contains(steps.ssl_check.outputs.ssl_log, 'SSL is enabled'))
        run: |-
          echo "SSL not enabled"
          exit 1

      - name: Faild if Hazelcast cluster is not formed
        if: (!contains(steps.client.outputs.members, 'Members [3]'))
        run: |-
          echo "Hazelcast cluster is not formed"
          exit 1